server:
  port: ${PORT:8080}

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/barberbooking
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    initialize: true
  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres