server:
  port: ${PORT:8080}

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/barberbooking
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  security:
    token:
      secret: "mySecretSuperSecret"
  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "admin"
    password: "123456"